package model.production;

import java.time.LocalDateTime;
import model.Product;
import model.employee.Employee;

public class ProductionWithProduct extends Production {

  private Product product;
  private String productSimpleName;
  private Employee producingEmployee;

  /**
   * Creates a record of production and attaches a product with it.
   *
   * @param productionId This production's id.
   * @param quantity The number of items produced
   * @param manufacturedOn The date and time this production was processed.
   * @param product The product produced.
   */
  public ProductionWithProduct(int productionId, int quantity, LocalDateTime manufacturedOn,
      Product product) {
    super(product.getId(), quantity, "", manufacturedOn);
    this.productionId = productionId;
    this.product = product;
    this.productSimpleName = product.getSimpleName();
  }

  /**
   * Creates a Production without a productionId for being generated by the database.
   *
   * @see #ProductionWithProduct(int, int, LocalDateTime, Product)
   */
  public ProductionWithProduct(Product product, int quantity, LocalDateTime manufacturedOn) {
    super(product.getId(), quantity, manufacturedOn);
    this.productionId = 0;
    this.product = product;
    this.productSimpleName = product.getSimpleName();
  }

  /**
   * Creates a Production record and attaches a Product to it.
   *
   * @param productionId The id of this production
   * @param quantity The number of products produced
   * @param serialNumber The serial number of this production
   * @param manufacturedOn The date that this production was processed
   * @param product The product that was produced
   */
  public ProductionWithProduct(int productionId, int quantity,
      String serialNumber, LocalDateTime manufacturedOn, Product product,
      Employee producingEmployee) {
    super(productionId, product.getId(), quantity, serialNumber, manufacturedOn);

    setProduct(product);
    setProducingEmployee(producingEmployee);
  }

  public Product getProduct() {
    return product;
  }

  public void setProduct(Product product) {
    this.product = product;
    this.productSimpleName = product.getSimpleName();
  }

  public Employee getProducingEmployee() {
    return producingEmployee;
  }

  public void setProducingEmployee(Employee producingEmployee) {
    this.producingEmployee = producingEmployee;
  }

  public String getProductSimpleName() {
    return productSimpleName;
  }

  public String getProducedByName() {
    return producingEmployee.getFirstName() + " " + producingEmployee.getLastName();
  }
}
